-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'DGI_VERIFICATION_VERIFIED';
ALTER TYPE "NotificationType" ADD VALUE 'DGI_VERIFICATION_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'DGI_VERIFICATION_MANUAL_REVIEW';
